.ORG #0000    ; Programın başlangıç adresini 0000h olarak belirler [cite: 3]
LDAA #0       ; A akümülatörüne başlangıç değeri olarak 0 yükler [cite: 4]
LDX #3        ; Döngü sayısını (çarpanı) X indeks yazmacına yükler [cite: 5]
CRP CLC       ; 'crp' etiketi oluşturur ve elde (carry) bayrağını temizler [cite: 6]
ADCA #2       ; A akümülatörüne 2 değerini (ve varsa eldeyi) ekler [cite: 7]
DEX           ; X indeks yazmacını 1 azaltır (döngü kontrolü) [cite: 8]
BNE CRP       ; X sıfır değilse 'crp' etiketine geri döner (döngü devam eder) [cite: 9]
STAA $0030    ; Çarpım sonucunu 0030h bellek adresine kaydeder [cite: 10]
.END          ; Programın sonu [cite: 11]